### ISSUE TITLE
React & Redux group project: Kanban board

### ISSUE THREAD

**Issue by yigitm** [yigitm/react-group-project#22]
We are two partners on this project: Jonathas de Sá Tavares  & Yiğit Mersin.

All cards are assigned & 3. team members' tasks are removed that are related to Dragon's.

GitHub Project Link: https://github.com/yigitm/react-group-project/projects/1

thank you for your time.

**Comment by Ghiftee** [comment]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽  @yigitm @jonathastavares 
Good job working on the project so far! 
✔️ You provided information about the people in your team
✔️ There is a link to your kanban board
However, there are some issues that you need to work on to go to the next project but you are almost there!
![](https://media.giphy.com/media/4GXUa4U05Q0JAM972c/giphy.gif)

## Required Changes ♻️
- [x] There are currently 20 cards on your Kanban board. However, there should be 17 cards since there are two people in your team. Kindly remove all cards for team member three and ensure the total cards are 17.
- [x] Kindly assign all tasks on the kanban board to team members. There should be a circle with the user's avatar on each card.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by rukundoeric** [comment]
Hi @yigitm,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
